// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/approval_status.proto

package approval

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_approval_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_approval_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_approval_status_proto_rawDescGZIP(), []int{0}
}

type ApprovalStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ApprovalType  int32                  `protobuf:"varint,3,opt,name=approval_type,json=approvalType,proto3" json:"approval_type,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalStatus) Reset() {
	*x = ApprovalStatus{}
	mi := &file_proto_approval_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalStatus) ProtoMessage() {}

func (x *ApprovalStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_approval_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalStatus.ProtoReflect.Descriptor instead.
func (*ApprovalStatus) Descriptor() ([]byte, []int) {
	return file_proto_approval_status_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApprovalStatus) GetApprovalType() int32 {
	if x != nil {
		return x.ApprovalType
	}
	return 0
}

func (x *ApprovalStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ApprovalStatus) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ApprovalStatus) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ApprovalStatus) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ApprovalStatusListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ApprovalStatus      `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalStatusListResponse) Reset() {
	*x = ApprovalStatusListResponse{}
	mi := &file_proto_approval_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalStatusListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalStatusListResponse) ProtoMessage() {}

func (x *ApprovalStatusListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_approval_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalStatusListResponse.ProtoReflect.Descriptor instead.
func (*ApprovalStatusListResponse) Descriptor() ([]byte, []int) {
	return file_proto_approval_status_proto_rawDescGZIP(), []int{2}
}

func (x *ApprovalStatusListResponse) GetStatuses() []*ApprovalStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type CreateApprovalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApprovalType  int32                  `protobuf:"varint,2,opt,name=approval_type,json=approvalType,proto3" json:"approval_type,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApprovalStatusRequest) Reset() {
	*x = CreateApprovalStatusRequest{}
	mi := &file_proto_approval_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApprovalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApprovalStatusRequest) ProtoMessage() {}

func (x *CreateApprovalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_approval_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApprovalStatusRequest.ProtoReflect.Descriptor instead.
func (*CreateApprovalStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_approval_status_proto_rawDescGZIP(), []int{3}
}

func (x *CreateApprovalStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApprovalStatusRequest) GetApprovalType() int32 {
	if x != nil {
		return x.ApprovalType
	}
	return 0
}

func (x *CreateApprovalStatusRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateApprovalStatusRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateApprovalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ApprovalType  int32                  `protobuf:"varint,3,opt,name=approval_type,json=approvalType,proto3" json:"approval_type,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApprovalStatusRequest) Reset() {
	*x = UpdateApprovalStatusRequest{}
	mi := &file_proto_approval_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApprovalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApprovalStatusRequest) ProtoMessage() {}

func (x *UpdateApprovalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_approval_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApprovalStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateApprovalStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_approval_status_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateApprovalStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateApprovalStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateApprovalStatusRequest) GetApprovalType() int32 {
	if x != nil {
		return x.ApprovalType
	}
	return 0
}

func (x *UpdateApprovalStatusRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdateApprovalStatusRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type DeleteApprovalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApprovalStatusRequest) Reset() {
	*x = DeleteApprovalStatusRequest{}
	mi := &file_proto_approval_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApprovalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApprovalStatusRequest) ProtoMessage() {}

func (x *DeleteApprovalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_approval_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApprovalStatusRequest.ProtoReflect.Descriptor instead.
func (*DeleteApprovalStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_approval_status_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteApprovalStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ApprovalStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        *ApprovalStatus        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalStatusResponse) Reset() {
	*x = ApprovalStatusResponse{}
	mi := &file_proto_approval_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalStatusResponse) ProtoMessage() {}

func (x *ApprovalStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_approval_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalStatusResponse.ProtoReflect.Descriptor instead.
func (*ApprovalStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_approval_status_proto_rawDescGZIP(), []int{6}
}

func (x *ApprovalStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApprovalStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApprovalStatusResponse) GetStatus() *ApprovalStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteApprovalStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApprovalStatusResponse) Reset() {
	*x = DeleteApprovalStatusResponse{}
	mi := &file_proto_approval_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApprovalStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApprovalStatusResponse) ProtoMessage() {}

func (x *DeleteApprovalStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_approval_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApprovalStatusResponse.ProtoReflect.Descriptor instead.
func (*DeleteApprovalStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_approval_status_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteApprovalStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteApprovalStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_approval_status_proto protoreflect.FileDescriptor

const file_proto_approval_status_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/approval_status.proto\x12\bapproval\"\a\n" +
	"\x05Empty\"\xc7\x01\n" +
	"\x0eApprovalStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rapproval_type\x18\x03 \x01(\x05R\fapprovalType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"R\n" +
	"\x1aApprovalStatusListResponse\x124\n" +
	"\bstatuses\x18\x01 \x03(\v2\x18.approval.ApprovalStatusR\bstatuses\"\x86\x01\n" +
	"\x1bCreateApprovalStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rapproval_type\x18\x02 \x01(\x05R\fapprovalType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"\x96\x01\n" +
	"\x1bUpdateApprovalStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rapproval_type\x18\x03 \x01(\x05R\fapprovalType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\"-\n" +
	"\x1bDeleteApprovalStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"~\n" +
	"\x16ApprovalStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x18.approval.ApprovalStatusR\x06status\"R\n" +
	"\x1cDeleteApprovalStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x90\x03\n" +
	"\x15ApprovalStatusService\x12N\n" +
	"\x15GetApprovalStatusList\x12\x0f.approval.Empty\x1a$.approval.ApprovalStatusListResponse\x12_\n" +
	"\x14CreateApprovalStatus\x12%.approval.CreateApprovalStatusRequest\x1a .approval.ApprovalStatusResponse\x12_\n" +
	"\x14UpdateApprovalStatus\x12%.approval.UpdateApprovalStatusRequest\x1a .approval.ApprovalStatusResponse\x12e\n" +
	"\x14DeleteApprovalStatus\x12%.approval.DeleteApprovalStatusRequest\x1a&.approval.DeleteApprovalStatusResponseB#Z!go-grpc-next-js-test/api/approvalb\x06proto3"

var (
	file_proto_approval_status_proto_rawDescOnce sync.Once
	file_proto_approval_status_proto_rawDescData []byte
)

func file_proto_approval_status_proto_rawDescGZIP() []byte {
	file_proto_approval_status_proto_rawDescOnce.Do(func() {
		file_proto_approval_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_approval_status_proto_rawDesc), len(file_proto_approval_status_proto_rawDesc)))
	})
	return file_proto_approval_status_proto_rawDescData
}

var file_proto_approval_status_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_approval_status_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: approval.Empty
	(*ApprovalStatus)(nil),               // 1: approval.ApprovalStatus
	(*ApprovalStatusListResponse)(nil),   // 2: approval.ApprovalStatusListResponse
	(*CreateApprovalStatusRequest)(nil),  // 3: approval.CreateApprovalStatusRequest
	(*UpdateApprovalStatusRequest)(nil),  // 4: approval.UpdateApprovalStatusRequest
	(*DeleteApprovalStatusRequest)(nil),  // 5: approval.DeleteApprovalStatusRequest
	(*ApprovalStatusResponse)(nil),       // 6: approval.ApprovalStatusResponse
	(*DeleteApprovalStatusResponse)(nil), // 7: approval.DeleteApprovalStatusResponse
}
var file_proto_approval_status_proto_depIdxs = []int32{
	1, // 0: approval.ApprovalStatusListResponse.statuses:type_name -> approval.ApprovalStatus
	1, // 1: approval.ApprovalStatusResponse.status:type_name -> approval.ApprovalStatus
	0, // 2: approval.ApprovalStatusService.GetApprovalStatusList:input_type -> approval.Empty
	3, // 3: approval.ApprovalStatusService.CreateApprovalStatus:input_type -> approval.CreateApprovalStatusRequest
	4, // 4: approval.ApprovalStatusService.UpdateApprovalStatus:input_type -> approval.UpdateApprovalStatusRequest
	5, // 5: approval.ApprovalStatusService.DeleteApprovalStatus:input_type -> approval.DeleteApprovalStatusRequest
	2, // 6: approval.ApprovalStatusService.GetApprovalStatusList:output_type -> approval.ApprovalStatusListResponse
	6, // 7: approval.ApprovalStatusService.CreateApprovalStatus:output_type -> approval.ApprovalStatusResponse
	6, // 8: approval.ApprovalStatusService.UpdateApprovalStatus:output_type -> approval.ApprovalStatusResponse
	7, // 9: approval.ApprovalStatusService.DeleteApprovalStatus:output_type -> approval.DeleteApprovalStatusResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_approval_status_proto_init() }
func file_proto_approval_status_proto_init() {
	if File_proto_approval_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_approval_status_proto_rawDesc), len(file_proto_approval_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_approval_status_proto_goTypes,
		DependencyIndexes: file_proto_approval_status_proto_depIdxs,
		MessageInfos:      file_proto_approval_status_proto_msgTypes,
	}.Build()
	File_proto_approval_status_proto = out.File
	file_proto_approval_status_proto_goTypes = nil
	file_proto_approval_status_proto_depIdxs = nil
}
