// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: proto/approval_status.proto

package approval

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApprovalStatusService_GetApprovalStatusList_FullMethodName = "/approval.ApprovalStatusService/GetApprovalStatusList"
	ApprovalStatusService_CreateApprovalStatus_FullMethodName  = "/approval.ApprovalStatusService/CreateApprovalStatus"
	ApprovalStatusService_UpdateApprovalStatus_FullMethodName  = "/approval.ApprovalStatusService/UpdateApprovalStatus"
	ApprovalStatusService_DeleteApprovalStatus_FullMethodName  = "/approval.ApprovalStatusService/DeleteApprovalStatus"
)

// ApprovalStatusServiceClient is the client API for ApprovalStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApprovalStatusServiceClient interface {
	GetApprovalStatusList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApprovalStatusListResponse, error)
	CreateApprovalStatus(ctx context.Context, in *CreateApprovalStatusRequest, opts ...grpc.CallOption) (*ApprovalStatusResponse, error)
	UpdateApprovalStatus(ctx context.Context, in *UpdateApprovalStatusRequest, opts ...grpc.CallOption) (*ApprovalStatusResponse, error)
	DeleteApprovalStatus(ctx context.Context, in *DeleteApprovalStatusRequest, opts ...grpc.CallOption) (*DeleteApprovalStatusResponse, error)
}

type approvalStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApprovalStatusServiceClient(cc grpc.ClientConnInterface) ApprovalStatusServiceClient {
	return &approvalStatusServiceClient{cc}
}

func (c *approvalStatusServiceClient) GetApprovalStatusList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ApprovalStatusListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalStatusListResponse)
	err := c.cc.Invoke(ctx, ApprovalStatusService_GetApprovalStatusList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalStatusServiceClient) CreateApprovalStatus(ctx context.Context, in *CreateApprovalStatusRequest, opts ...grpc.CallOption) (*ApprovalStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalStatusResponse)
	err := c.cc.Invoke(ctx, ApprovalStatusService_CreateApprovalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalStatusServiceClient) UpdateApprovalStatus(ctx context.Context, in *UpdateApprovalStatusRequest, opts ...grpc.CallOption) (*ApprovalStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalStatusResponse)
	err := c.cc.Invoke(ctx, ApprovalStatusService_UpdateApprovalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalStatusServiceClient) DeleteApprovalStatus(ctx context.Context, in *DeleteApprovalStatusRequest, opts ...grpc.CallOption) (*DeleteApprovalStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteApprovalStatusResponse)
	err := c.cc.Invoke(ctx, ApprovalStatusService_DeleteApprovalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApprovalStatusServiceServer is the server API for ApprovalStatusService service.
// All implementations must embed UnimplementedApprovalStatusServiceServer
// for forward compatibility.
type ApprovalStatusServiceServer interface {
	GetApprovalStatusList(context.Context, *Empty) (*ApprovalStatusListResponse, error)
	CreateApprovalStatus(context.Context, *CreateApprovalStatusRequest) (*ApprovalStatusResponse, error)
	UpdateApprovalStatus(context.Context, *UpdateApprovalStatusRequest) (*ApprovalStatusResponse, error)
	DeleteApprovalStatus(context.Context, *DeleteApprovalStatusRequest) (*DeleteApprovalStatusResponse, error)
	mustEmbedUnimplementedApprovalStatusServiceServer()
}

// UnimplementedApprovalStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApprovalStatusServiceServer struct{}

func (UnimplementedApprovalStatusServiceServer) GetApprovalStatusList(context.Context, *Empty) (*ApprovalStatusListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApprovalStatusList not implemented")
}
func (UnimplementedApprovalStatusServiceServer) CreateApprovalStatus(context.Context, *CreateApprovalStatusRequest) (*ApprovalStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApprovalStatus not implemented")
}
func (UnimplementedApprovalStatusServiceServer) UpdateApprovalStatus(context.Context, *UpdateApprovalStatusRequest) (*ApprovalStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApprovalStatus not implemented")
}
func (UnimplementedApprovalStatusServiceServer) DeleteApprovalStatus(context.Context, *DeleteApprovalStatusRequest) (*DeleteApprovalStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteApprovalStatus not implemented")
}
func (UnimplementedApprovalStatusServiceServer) mustEmbedUnimplementedApprovalStatusServiceServer() {}
func (UnimplementedApprovalStatusServiceServer) testEmbeddedByValue()                               {}

// UnsafeApprovalStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApprovalStatusServiceServer will
// result in compilation errors.
type UnsafeApprovalStatusServiceServer interface {
	mustEmbedUnimplementedApprovalStatusServiceServer()
}

func RegisterApprovalStatusServiceServer(s grpc.ServiceRegistrar, srv ApprovalStatusServiceServer) {
	// If the following call panics, it indicates UnimplementedApprovalStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApprovalStatusService_ServiceDesc, srv)
}

func _ApprovalStatusService_GetApprovalStatusList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalStatusServiceServer).GetApprovalStatusList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalStatusService_GetApprovalStatusList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalStatusServiceServer).GetApprovalStatusList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalStatusService_CreateApprovalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApprovalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalStatusServiceServer).CreateApprovalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalStatusService_CreateApprovalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalStatusServiceServer).CreateApprovalStatus(ctx, req.(*CreateApprovalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalStatusService_UpdateApprovalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApprovalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalStatusServiceServer).UpdateApprovalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalStatusService_UpdateApprovalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalStatusServiceServer).UpdateApprovalStatus(ctx, req.(*UpdateApprovalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalStatusService_DeleteApprovalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApprovalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalStatusServiceServer).DeleteApprovalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalStatusService_DeleteApprovalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalStatusServiceServer).DeleteApprovalStatus(ctx, req.(*DeleteApprovalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApprovalStatusService_ServiceDesc is the grpc.ServiceDesc for ApprovalStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApprovalStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "approval.ApprovalStatusService",
	HandlerType: (*ApprovalStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApprovalStatusList",
			Handler:    _ApprovalStatusService_GetApprovalStatusList_Handler,
		},
		{
			MethodName: "CreateApprovalStatus",
			Handler:    _ApprovalStatusService_CreateApprovalStatus_Handler,
		},
		{
			MethodName: "UpdateApprovalStatus",
			Handler:    _ApprovalStatusService_UpdateApprovalStatus_Handler,
		},
		{
			MethodName: "DeleteApprovalStatus",
			Handler:    _ApprovalStatusService_DeleteApprovalStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/approval_status.proto",
}
