import type { Metadata } from "next";
import { Roboto, Noto_Sans_Myanmar } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import '@mantine/core/styles.css';
import { ColorSchemeScript } from '@mantine/core';
import { ShellWrapper } from "./components/ShellWrapper";
import { ThemeProvider } from './context/ThemeContext';
import { ThemedMantineProvider } from './components/ThemedMantineProvider';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

const myanmar = Noto_Sans_Myanmar({
  weight: ['400', '500', '700'],
  subsets: ['myanmar'],
  variable: '--font-myanmar',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${myanmar.variable}`}>
        <ThemeProvider>
          <ThemedMantineProvider>
            <ShellWrapper>
              {children}
            </ShellWrapper>
          </ThemedMantineProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
